column_limit: 100
indent_width: 2
use_tab: false
tab_width: 1
continuation_indent_width: 2
spaces_before_call: 0
keep_simple_control_block_one_line: true
keep_simple_function_one_line: true
align_args: true
break_after_functioncall_lp: true
break_before_functioncall_rp: true
align_parameter: false
chop_down_parameter: false
align_table_field: true
break_after_table_lb: true
break_before_table_rb: true
chop_down_kv_table: true
extra_sep_at_table_end: true
break_after_operator: true
double_quote_to_single_quote: true
single_quote_to_double_quote: false
