# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# icon options =  ❯   
# Top left:     directory(gitbranch) ● ●

format = """
$directory(bold green)(\\($git_branch\\)) $all $fill $time\
$line_break\
$character
"""

[character]
format = "$symbol "
success_symbol = "[➜](bold green)"
vicmd_symbol = "[](green)"

[fill]
symbol = " "

[time]
format = "[$time]($style)"
disabled = false

[git_status]
format = """
([\
($conflicted )\
[($stashed )](blue)\
$deleted\
($renamed )\
[($modified )](green)\
$staged\
$untracked\
[$ahead_behind](yellow)\
]($style) )"""
stashed = ""
modified = "●"

[git_branch]
format = "[$branch(:$remote_branch)]($style)"
style = "italic blue"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold green"

[aws]
disabled = true
symbol = "☁"

[gcloud]
symbol = ""
disabled = true

[lua]
format = "[$symbol ($version )]($style)"
symbol = ""
