# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# icon options =  ❯   
# Top left:     directory(gitbranch) ● ●

format = """
$directory(bold green)(\\($git_branch\\)) $git_status\
$git_commit\
$git_state\
$line_break\
$jobs\
$character
"""

right_format = "$all $time"
# Remove the newline that separates prompts, it eats up too much space
add_newline = false

[character]
format = "$symbol "
success_symbol = "[➜](bold purple) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[](#137628) "

[time]
format = "[$time]($style)"
style = "dimmed #818181"
disabled = false

[git_status]
format = """
([\
($conflicted )\
[($stashed )](yellow)\
$deleted\
($renamed )\
[($modified )](green)\
$staged\
$untracked\
[$ahead_behind](yellow)\
]($style) )"""
stashed = ""
modified = "●"

[git_branch]
format = "[$branch(:$remote_branch)]($style)"
style = "italic blue"
symbol = " "

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold green"
read_only = " "

[gcloud]
symbol = ""
disabled = true

[lua]
symbol = " "
format = " [$symbol($version)]($style)"

[golang]
symbol = " "
format = "[$symbol($version)]($style)"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[haskell]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[spack]
symbol = "🅢 "

[rust]
symbol = " "
